"""Fixed texts the workers send without the agent (approval cards, buttons, feedback acks, fallbacks), in the
person's language. Keep them short and spoken — they sit in the same chat as the agent's own messages, so they
must not read like system output (no ids, no hashes, no "Sent (id …)")."""
from __future__ import annotations

TEXTS: dict[str, dict[str, str]] = {
    "en": {
        "draft": "Draft",
        "draft_reply": "Draft (reply in thread)",
        "draft_doc": "Draft — {label}",
        "to": "To: {to}",
        "subject": "Subject: {subject}",
        "title": "Title: {title}",
        "parent": "In: {parent}",
        "btn_send": "✅ Send",
        "btn_create": "✅ Create",
        "btn_edit": "✏️ Edit",
        "btn_cancel": "❌ Cancel",
        "sent": "Sent 👍",
        "send_failed": "Couldn't send it. Tap Send and I'll try again.",
        "send_failed_thread": "I can't find that mail thread in your inbox, so the reply has nowhere to go. "
                              "Want it as a new mail instead? Just tell me.",
        "send_failed_auth": "Couldn't send it, the mail connection needs a fresh sign-in. Tell me and I'll send you the link.",
        "cancelled": "Cancelled, nothing was sent.",
        "edit_prompt": "Okay, send me the corrected text as your next message.",
        "no_draft": "There's no draft open right now.",
        "draft_changed": "The draft changed, approve the newest one",
        "nothing_to_edit": "Nothing to edit",
        "ack_sent": "Sent",
        "ack_send_failed": "Couldn't send",
        "ack_cancelled": "Cancelled",
        "ack_waiting_edit": "Waiting for your correction",
        "doc_created": "📄 {title}\n{url}",
        "doc_created_nolink": "📄 {title} is ready.",
        "doc_failed": "I couldn't create the document, I'll try again a bit later.",
        "fb_useful": "👍 useful",
        "fb_noise": "👎 noise",
        "fb_mute": "🔇 mute thread",
        "noted_useful": "Noted, thanks 👍",
        "noted_noise": "Got it, less of that 👎",
        "unknown_notification": "I don't know that notification anymore",
        "nothing_to_mute": "Nothing to mute",
        "muted": "Muted that thread 🔇",
        "brief_quiet": "Good morning ☀️ Nothing important came in since yesterday. Enjoy the quiet.",
        "brief_header": "Good morning ☀️ Since yesterday:",
        "remind_set": "⏰ I'll remind you {when}: {note}",
        "stuck": "I got stuck on that one, could you ask again?",
    },
    "tr": {
        "draft": "Taslak",
        "draft_reply": "Taslak (aynı konuya yanıt)",
        "draft_doc": "Taslak — {label}",
        "to": "Kime: {to}",
        "subject": "Konu: {subject}",
        "title": "Başlık: {title}",
        "parent": "Nerede: {parent}",
        "btn_send": "✅ Gönder",
        "btn_create": "✅ Oluştur",
        "btn_edit": "✏️ Düzelt",
        "btn_cancel": "❌ Vazgeç",
        "sent": "Gönderdim 👍",
        "send_failed": "Gönderemedim. Gönder'e bir daha basarsan tekrar denerim.",
        "send_failed_thread": "Bu mail zincirini gelen kutunda bulamadım, cevabın gidecek yeri yok. "
                              "İstersen yeni mail olarak göndereyim, söylemen yeter.",
        "send_failed_auth": "Gönderemedim, mail bağlantısının yenilenmesi gerekiyor. Söyle, bağlantı linkini yollayayım.",
        "cancelled": "Vazgeçtim, bir şey gönderilmedi.",
        "edit_prompt": "Tamam, düzeltilmiş halini yaz, onu göndereyim.",
        "no_draft": "Şu an açık bir taslak yok.",
        "draft_changed": "Taslak değişti, en yenisini onayla",
        "nothing_to_edit": "Düzeltilecek bir şey yok",
        "ack_sent": "Gönderildi",
        "ack_send_failed": "Gönderilemedi",
        "ack_cancelled": "Vazgeçildi",
        "ack_waiting_edit": "Düzeltmeni bekliyorum",
        "doc_created": "📄 {title}\n{url}",
        "doc_created_nolink": "📄 {title} hazır.",
        "doc_failed": "Belgeyi oluşturamadım, biraz sonra tekrar deneyeyim.",
        "fb_useful": "👍 işe yaradı",
        "fb_noise": "👎 gereksiz",
        "fb_mute": "🔇 bu konuyu sustur",
        "noted_useful": "Not aldım, sağ ol 👍",
        "noted_noise": "Tamam, bunlardan daha az 👎",
        "unknown_notification": "Bu bildirimi artık bulamıyorum",
        "nothing_to_mute": "Susturacak bir şey yok",
        "muted": "Bu konuyu susturdum 🔇",
        "brief_quiet": "Günaydın ☀️ Dünden beri önemli bir şey gelmedi. Sakin bir gün.",
        "brief_header": "Günaydın ☀️ Dünden beri:",
        "remind_set": "⏰ {when} hatırlatırım: {note}",
        "stuck": "Bu sefer takıldım, bir daha sorar mısın?",
    },
    "de": {
        "draft": "Entwurf",
        "draft_reply": "Entwurf (Antwort im Thread)",
        "draft_doc": "Entwurf — {label}",
        "to": "An: {to}",
        "subject": "Betreff: {subject}",
        "title": "Titel: {title}",
        "parent": "In: {parent}",
        "btn_send": "✅ Senden",
        "btn_create": "✅ Anlegen",
        "btn_edit": "✏️ Ändern",
        "btn_cancel": "❌ Abbrechen",
        "sent": "Gesendet 👍",
        "send_failed": "Konnte nicht senden. Tipp nochmal auf Senden, dann versuche ich es erneut.",
        "send_failed_thread": "Ich finde diesen Mail-Thread nicht in deinem Postfach, die Antwort hat kein Ziel. "
                              "Sag Bescheid, dann schicke ich sie als neue Mail.",
        "send_failed_auth": "Konnte nicht senden, die Mail-Verbindung muss neu bestätigt werden. Sag Bescheid, dann schicke ich dir den Link.",
        "cancelled": "Abgebrochen, nichts wurde gesendet.",
        "edit_prompt": "Okay, schick mir den korrigierten Text als nächste Nachricht.",
        "no_draft": "Gerade ist kein Entwurf offen.",
        "draft_changed": "Der Entwurf hat sich geändert, bitte den neuesten bestätigen",
        "nothing_to_edit": "Nichts zu ändern",
        "ack_sent": "Gesendet",
        "ack_send_failed": "Senden fehlgeschlagen",
        "ack_cancelled": "Abgebrochen",
        "ack_waiting_edit": "Warte auf deine Korrektur",
        "doc_created": "📄 {title}\n{url}",
        "doc_created_nolink": "📄 {title} ist fertig.",
        "doc_failed": "Ich konnte das Dokument nicht anlegen, ich versuche es später nochmal.",
        "fb_useful": "👍 nützlich",
        "fb_noise": "👎 unnötig",
        "fb_mute": "🔇 Thread stumm",
        "noted_useful": "Notiert, danke 👍",
        "noted_noise": "Verstanden, weniger davon 👎",
        "unknown_notification": "Diese Benachrichtigung finde ich nicht mehr",
        "nothing_to_mute": "Nichts stummzuschalten",
        "muted": "Thread stummgeschaltet 🔇",
        "brief_quiet": "Guten Morgen ☀️ Seit gestern kam nichts Wichtiges. Ein ruhiger Tag.",
        "brief_header": "Guten Morgen ☀️ Seit gestern:",
        "remind_set": "⏰ Ich erinnere dich {when}: {note}",
        "stuck": "Da bin ich hängen geblieben, fragst du nochmal?",
    },
}


def phrase(lang: str | None, key: str, **kw: object) -> str:
    """Text `key` in `lang` (ISO 639-1; unknown or empty -> English), with {placeholders} filled in."""
    table = TEXTS.get((lang or "en").split("-")[0].lower(), TEXTS["en"])
    text = table.get(key) or TEXTS["en"][key]
    return text.format(**kw) if kw else text
